### ISSUE TITLE
Is it ready to test?

### ISSUE THREAD

**Issue by EgyptianM** [FahimAnzamDip/triangle-pos#1]
Hi,
Is the script ready to test or not yet?

**Comment by FahimAnzamDip** [comment]
> Hi,
> Is the script ready to test or not yet?

Not yet. Core features are almost ready to use.

**Comment by EgyptianM** [comment]
Yes I tested it, it works but you need to add at least 1 currency to db or it won't work.
Good work.
I can help you with it if you need.
Jazak Allah khiran
