### ISSUE TITLE
Profit on Dashboard & Reports

### ISSUE THREAD

**Issue by JohanQuiroa** [FahimAnzamDip/triangle-pos#10]
Profits are calculated by deducting product cost price from revenue but it is not multiplying the cost price by quantity.

Here is the sample fix:
`$product_costs += $saleDetail->product->product_cost * $saleDetail->quantity;`

**Comment by sipoun** [comment]
i have this issue on the HomeController 

$product_costs += $saleDetail->product->product_cost * $saleDetail->quantity;

line 30

message 
ErrorException
Attempt to read property "product_cost" on null
