### ISSUE TITLE
app/Http/Controllers/HomeController.php 

### ISSUE THREAD

**Issue by sipoun** [FahimAnzamDip/triangle-pos#11]
Line 30

ErrorException
Attempt to read property "product_cost" on null

**Comment by EgyptianM** [comment]
You have deleted a product which exists in a sale or more.
I'll post a fix soon.

**Comment by EgyptianM** [comment]
Repace line 30 with this code

         if (!is_null($saleDetail->product)) {
                    $product_costs += $saleDetail->product->product_cost * $saleDetail->quantity;
         }
