### ISSUE TITLE
What approach do use with yajra datatables?

### ISSUE THREAD

**Issue by EgyptianM** [FahimAnzamDip/triangle-pos#12]
I'm trying to add a new module and use yajra datatables  with it like the rest of the modules but I can't figure it out
Can you help with that?

**Comment by EgyptianM** [comment]
When I try to use datatables it creates files in the app directory even if I used a specific module

            `PS C:\Wamp.NET\sites\tripos> php artisan module:use Language
            Module [Language] used successfully.
            PS C:\Wamp.NET\sites\tripos> php artisan datatables:make Language --model
            DataTable created successfully.
            PS C:\Wamp.NET\sites\tripos>`

the file is created under the app folder.

**Comment by FahimAnzamDip** [comment]
The file will be created under app folder but you can move the file into any folder you want. Then change the namespace. It should work.
