### ISSUE TITLE
Cannot print PDF i already instal WKHTML and its not working PDF.js v2.3.164 (build: 12ff2527)

### ISSUE THREAD

**Issue by adinugro88** [FahimAnzamDip/triangle-pos#16]
error when print pdf

**Comment by EgyptianM** [comment]
Me too
I'm trying to use another library but didn't finish it yet.

**Comment by EgyptianM** [comment]
It works fine on my server though but not on the local server unfortunately.

**Comment by JemCdo** [comment]
@EgyptianM @adinugro88 you can instead use this https://github.com/barryvdh/laravel-dompdf

**Comment by FahimAnzamDip** [comment]
Please refer https://github.com/barryvdh/laravel-snappy
