### ISSUE TITLE
419 Maybe, the CSRF token is missing.

### ISSUE THREAD

**Issue by MrX123123** [FahimAnzamDip/triangle-pos#19]
Hi,

when using your demo server I am getting this error message: "419 Maybe, the CSRF token is missing."
I also got this error message on my local test server. Was fixed with installation of redis and memcached. Maybe this is missing on your test server as well?

BR

**Comment by adinugro88** [comment]
im using this code and its work https://www.youtube.com/watch?v=l90RmmUTfv4
