### ISSUE TITLE
Production error on login

### ISSUE THREAD

**Issue by Michael-254** [FahimAnzamDip/triangle-pos#24]
Upon deployment on production, this occurs on attempt
Symfony\Component\HttpFoundation\Response::setContent(): Argument #1 ($content) must be of type ?string,

**Comment by malitufail** [comment]
Did you figure out the issue?

**Comment by Michael-254** [comment]
Nope I had to recreate a new Controller for auth

**Comment by malitufail** [comment]
I have been trying to figure it out for over a month now, locally it is running fine but after deployment on the shared hosting it is giving this error and routes errors

**Comment by malitufail** [comment]
"Nope I had to recreate a new Controller for auth"

Did that worked for you?

**Comment by MrX123123** [comment]
> I have been trying to figure it out for over a month now, locally it is running fine but after deployment on the shared hosting it is giving this error and routes errors

same php and laravel version?

**Comment by malitufail** [comment]
No php

> > I have been trying to figure it out for over a month now, locally it is running fine but after deployment on the shared hosting it is giving this error and routes errors
> 
> same php and laravel version?

No, laravel version is same but when i set the php to 8.0 it says dependencies for 8.1.2 so i update it to 8.1.2. I have tried every possible way but cant figure this out

**Comment by Michael-254** [comment]
Yes this worked for me

**Comment by malitufail** [comment]
> Yes this worked for me

Can you please help me out with this?

**Comment by alpondith** [comment]
I solved this issue by changing app/Http/Controllers/Auth/LoginController.php 

This issue is happening because of authenticated() function has been edited. 

Update this function according to https://laravel.com/docs/7.x/authentication#authenticating-users

**Comment by devmpemba** [comment]
Thanks man, this helps me a lot. Gracias!
