### ISSUE TITLE
when deleting category a "BadMethodCallException" is showing 

### ISSUE THREAD

**Issue by Michlaguardia99** [FahimAnzamDip/triangle-pos#25]
Call to undefined method Illuminate\Database\Eloquent\Relations\HasMany::isNotEmpty()

 public function destroy($id) {

        abort_if(Gate::denies('access_product_categories'), 403);
        $category = Category::findOrFail($id);
        if ($category->products()->isNotEmpty()) {

            return back()->withErrors('Can\'t delete beacuse there are products associated with this category.');

        }
        $category->delete();
        toast('Product Category Deleted!', 'warning');

        return redirect()->route('product-categories.index');

**Comment by Sanmich14** [comment]
one more thing, i uploaded the project to hostinger but when i am uploading new image  avatar/profile image , its says updated but the image is not showing 
Failed to load resource: the server responded with a status of 404 ()

**Comment by MrX123123** [comment]
Please have a look at the laravel docu. Looks like this is missing: php artisan storage:link
