### ISSUE TITLE
Error Failed to load PDF document

### ISSUE THREAD

**Issue by EgyptianM** [FahimAnzamDip/triangle-pos#3]
When I try to print invoice I get this error.

Error
Failed to load PDF document

**Comment by FahimAnzamDip** [comment]
It uses Laravel Snappy package for PDF. Follow this https://github.com/barryvdh/laravel-snappy to install snappy in your machine or if you are on Linux already I included the composer dependency for wkhtmltopdf that should work.

**Comment by EgyptianM** [comment]
Hi,
I installed snappy for windows and it still the same error.

Can't you use another package that doesn't require any programs to be installed on the system?

**Comment by EgyptianM** [comment]
I just returned the view itself with some modifications
That's much better
