### ISSUE TITLE
Fresh installation getting error

### ISSUE THREAD

**Issue by mzbk** [FahimAnzamDip/triangle-pos#31]
Fresh installation getting the below error when updating the composer.
The target class [CommandMakeCommand] does not exist.

**Comment by JohanQuiroa** [comment]
@mzbk try updating the modules.php under config to include the fully qualified class name like below:
`'commands' => [
        Nwidart\Modules\Commands\CommandMakeCommand::class,
        Nwidart\Modules\Commands\ControllerMakeCommand::class,
        Nwidart\Modules\Commands\DisableCommand::class,
        Nwidart\Modules\Commands\DumpCommand::class,
        Nwidart\Modules\Commands\EnableCommand::class,
        Nwidart\Modules\Commands\EventMakeCommand::class,
        Nwidart\Modules\Commands\JobMakeCommand::class,
        Nwidart\Modules\Commands\ListenerMakeCommand::class,
        Nwidart\Modules\Commands\MailMakeCommand::class,
        Nwidart\Modules\Commands\MiddlewareMakeCommand::class,
        Nwidart\Modules\Commands\NotificationMakeCommand::class,
        Nwidart\Modules\Commands\ProviderMakeCommand::class,
        Nwidart\Modules\Commands\RouteProviderMakeCommand::class,
        Nwidart\Modules\Commands\InstallCommand::class,
        Nwidart\Modules\Commands\ListCommand::class,
        Nwidart\Modules\Commands\ModuleDeleteCommand::class,
        Nwidart\Modules\Commands\ModuleMakeCommand::class,
        Nwidart\Modules\Commands\FactoryMakeCommand::class,
        Nwidart\Modules\Commands\PolicyMakeCommand::class,
        Nwidart\Modules\Commands\RequestMakeCommand::class,
        Nwidart\Modules\Commands\RuleMakeCommand::class,
        Nwidart\Modules\Commands\MigrateCommand::class,
        Nwidart\Modules\Commands\MigrateRefreshCommand::class,
        Nwidart\Modules\Commands\MigrateResetCommand::class,
        Nwidart\Modules\Commands\MigrateRollbackCommand::class,
        Nwidart\Modules\Commands\MigrateStatusCommand::class,
        Nwidart\Modules\Commands\MigrationMakeCommand::class,
        Nwidart\Modules\Commands\ModelMakeCommand::class,
        Nwidart\Modules\Commands\PublishCommand::class,
        Nwidart\Modules\Commands\PublishConfigurationCommand::class,
        Nwidart\Modules\Commands\PublishMigrationCommand::class,
        Nwidart\Modules\Commands\PublishTranslationCommand::class,
        Nwidart\Modules\Commands\SeedCommand::class,
        Nwidart\Modules\Commands\SeedMakeCommand::class,
        Nwidart\Modules\Commands\SetupCommand::class,
        Nwidart\Modules\Commands\UnUseCommand::class,
        Nwidart\Modules\Commands\UpdateCommand::class,
        Nwidart\Modules\Commands\UseCommand::class,
        Nwidart\Modules\Commands\ResourceMakeCommand::class,
        Nwidart\Modules\Commands\TestMakeCommand::class,
        Nwidart\Modules\Commands\LaravelModulesV6Migrator::class,
    ],`

**Comment by alpondith** [comment]
update composer.json file for laravel-modules package.

fix  laravel-modules package version to 8.2 

"nwidart/laravel-modules": "8.2",
