### ISSUE TITLE
Purchase Business Process (Wrong)

### ISSUE THREAD

**Issue by cndraa** [FahimAnzamDip/triangle-pos#36]
I think your Purchase Business process is wrong buddy. i think the amount of unit price must input with user, not automatically filled by price of product. so, unit price must free input. Of course, you should create another Livewire called ProductPurchaseCart. So, that livewire only contain for Purchase Feature. but all the feature is awesome man! you are great! i hope you can take my advice and update your code soon! God Speed!

**Comment by FahimAnzamDip** [comment]
I wouldn't say it's wrong. But this feature will be nice edition. Will look into that, Thank you.

**Comment by cndraa** [comment]
Yup! Your all feature is Awesome man.. but in the Real life business process, Purchase price must be an Free input depends on supplier price not from our product Price. But, thanks again for your Application, it’s awesome, just need a little Changes on Purchase, not Purchase Return or else, just in Purchase Feature. Will waiting for further update in your Purchase Feature mate! Thanks a lot! 🙌🏻Sent from my iPhoneOn 1 Jul 2023, at 21.34, Fahim Anzam Dip ***@***.***> wrote:﻿
I wouldn't say it's wrong. But this feature will be nice edition. Will look into that, Thank you.

**Comment by cndraa** [comment]
Hei Fahim! Me Again. First of all, thanks a lot for your POS System, it's
open public and it help a lot on my Grocery Shop. But now, i try to hosting
it, so i can open the POS in anywhere and whenever i want to open, either
from phone, ipad or PC. But, i got an issue when i tried to hosting it,
it's about "Mix manifest does not exist", i will give attachment screenshot
below regarding the error i got. i tried another suggestion from
Stackoverflow etc, but it doesn't work, please help to solve this issue, i
really need, thankyou for your time.

Pada tanggal Min, 2 Jul 2023 pukul 13.08 Didimus Candra <
***@***.***> menulis:

> Yup! Your all feature is Awesome man.. but in the Real life business
> process, Purchase price must be an Free input depends on supplier price not
> from our product Price. But, thanks again for your Application, it’s
> awesome, just need a little Changes on Purchase, not Purchase Return or
> else, just in Purchase Feature. Will waiting for further update in your
> Purchase Feature mate! Thanks a lot! 🙌🏻
>
> Sent from my iPhone
>

**Comment by FahimAnzamDip** [comment]
Please provide the screenshot.

**Comment by cndraa** [comment]
Below the screenshot Fahim.

Pada tanggal Rab, 26 Jul 2023 pukul 16.26 Fahim Anzam Dip <
***@***.***> menulis:

**Comment by FahimAnzamDip** [comment]
There is no screenshot here.

**Comment by cndraa** [comment]
All good now mate! Thankyou very much.Sent from my iPhoneOn 26 Jul 2023, at 16.58, Fahim Anzam Dip ***@***.***> wrote:﻿
Run "npm install then npm run prod" in the local environment after that try to host it.

**Comment by cndraa** [comment]
Greeting Mr. Fahim!
Can you help me to edit your Purchase Business Process, earlier i sent a
comment into your Github Repository, this is my comment
https://github.com/FahimAnzamDip/triangle-pos/issues/36#issue-1757419922.
Can you help to do enhancement to that Purchase Feature ? Really need that
sir, i hope you can considering it. Thanks a lot!

Pada tanggal Sab, 1 Jul 2023 pukul 21.34 Fahim Anzam Dip <
***@***.***> menulis:

**Comment by cndraa** [comment]
Greetings Mr.Fahim!
How's about my request for Purchase Feature? I Really need that for my Shop Business, i would like to pay you if you want, just send me your Personal Email and we can talk about it, just need minor enhancement in Purchase Feature. Will waiting your response. Thanks!

**Comment by FahimAnzamDip** [comment]
The feature is added please check the latest code. Thank you.
