### ISSUE TITLE
Profile image isn't updated

### ISSUE THREAD

**Issue by Zeon-ai** [FahimAnzamDip/triangle-pos#38]
The notifications show the profile is updated. But the profile picture still the default one, the image was there in the folder yet it wasn't called. Strangely this only occur to profile picture, the product image is showing fine. Does you know the cause of this? Thanks in advance.

**Comment by Zeon-ai** [comment]
![image](https://github.com/FahimAnzamDip/triangle-pos/assets/59920507/5db5e383-be25-4c65-a0f0-3a404633d836)

**Comment by Zeon-ai** [comment]
Owh yeah i am using it for my homework, will credit you ofc~ (This didn't happen last time, but suddenly this is happening. I don't know what the cause of it).

**Comment by FahimAnzamDip** [comment]
Hello, I hope you are well. Please check your console for any kind of errors also did you ran the "php artisan storage:link" command?

**Comment by Zeon-ai** [comment]
Hi thanks for the reply. I did ran "php artisan storage:link". 

The image is working fine in product table. Yet when it's coming into profile picture it wasn't working, the console said it's wasn't any error of it. 

The profile picture get uploaded into the database and into the temp folder and it working. Yet when called It into profile tabs, the profile always prefer the default one instead the uploaded image. 

I will try to learn more about the console maybe i did something wrong with the settings.
