### ISSUE TITLE
The requested quantity is not available in stock.

### ISSUE THREAD

**Issue by EgyptianM** [FahimAnzamDip/triangle-pos#4]
When I try to add purchases it says The requested quantity is not available in stock.
I think purchase should be added to the stock not subtracted from it and sales should be subtracted from stock.

Can you please explain the logic of the script, how it works?

**Comment by FahimAnzamDip** [comment]
Got it. It does add to stock. But maybe your are trying to put the quantity higher than current stock and getting this warning. It's seems like a bug I have to fix. Because It shouldn't check current stock for Purchases.
