### ISSUE TITLE
 Class "RealRashid\SweetAlert\SweetAlertServiceProvider" not found

### ISSUE THREAD

**Issue by saif-4467** [FahimAnzamDip/triangle-pos#40]
Please help me to fix this issue. 
![image](https://github.com/FahimAnzamDip/triangle-pos/assets/101814014/0f431e07-fd01-41f7-ae7d-d277a84eea05)

**Comment by FahimAnzamDip** [comment]
Please follow the local installation instructions and use latest php version. I installed in my local machine with same instruction step by step didn't have any problem.
