### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long

### ISSUE THREAD

**Issue by Mo7mud** [FahimAnzamDip/triangle-pos#6]
Running `php artisan migrate --seed` results in this error

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too  long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))`

**Comment by manyang-megantoro** [comment]
Change engine in config/database.php to innoDB

'mysql' => [
            'engine' => 'InnoDB',
        ],
