### ISSUE TITLE
Creating new pages

### ISSUE THREAD

**Issue by SilentProdigy** [FahimAnzamDip/triangle-pos#62]
How would you create new pages here? I followed file structures for Modules but not getting right path for routes.

**Comment by SilentProdigy** [comment]
@FahimAnzamDip @mzbk

**Comment by FahimAnzamDip** [comment]
I used laravel modules in this project. So if you can refer https://nwidart.com/laravel-modules/v6/introduction here then I think you will understand the project structure more. Thanks
