### ISSUE TITLE
Why hide the routes?!!!!

### ISSUE THREAD

**Issue by timothykimemia** [FahimAnzamDip/triangle-pos#9]
![Screenshot 2021-12-12 192458](https://user-images.githubusercontent.com/5364357/145720591-8fce44cf-326c-4a9b-9e6c-a3b1b29875bb.png)
Thank you and I love the project.. my question is why to hide the routes cause I am trying to host on a Cpanel shared server...
Please assist

**Comment by FahimAnzamDip** [comment]
Routes are not hidden, You can find routes for specific module in their Module folder.

**Comment by timothykimemia** [comment]
I did not realise this is a library for creating modules
`"nwidart/laravel-modules": "^8.2"`
Sorry, used to laravel native style of declaring on the `routes` directory

**Comment by FahimAnzamDip** [comment]
No problem.
